
/* =========================================================================================
 * Copyright © 2013-2017 the kamon project <http://kamon.io/>
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 * =========================================================================================
 */


val sprayCan      = "io.spray" %%  "spray-can"      % "1.3.3"
val sprayRouting  = "io.spray" %%  "spray-routing"  % "1.3.3"
val sprayClient   = "io.spray" %%  "spray-client"   % "1.3.3"

name := "kamon-spray"
scalaVersion := "2.11.12"
crossScalaVersions := Seq("2.11.12")
libraryDependencies ++= Seq(
  sprayCan % "provided",
  sprayRouting % "provided",
  sprayClient % "provided",
  "io.kamon"           % "kanela-agent"     % "1.0.9" % "provided",
  "com.typesafe.akka" %% "akka-actor"       % "2.5.17" % "provided",
  "com.typesafe.akka" %% "akka-slf4j"       % "2.5.17" % "provided",
  "io.kamon"          %% "kamon-bundle"     % "2.2.0",
  "io.kamon"          %% "kamon-testkit"    % "2.2.0" % "test",
  "ch.qos.logback"     % "logback-classic"  % "1.2.3" % "test",
  "com.typesafe.akka" %% "akka-testkit"     % "2.5.17" % "test"
)

// We are replacing the "date-time" part of the version generated by sbt-dynver so that we
// get the same version value, even when re-applying settings during cross actions that
// might take longer than a minute to complete.
version ~= (_.replaceAll("[+]\\d{8}[-]\\d{4}", "-dirty"))
dynver ~= (_.replaceAll("[+]\\d{8}[-]\\d{4}", "-dirty"))
publishTo := sonatypePublishToBundle.value
pomExtra :=  {
  <url>http://kamon.io</url>
  <scm>
    <url>git://github.com/kamon-io/Kamon.git</url>
    <connection>scm:git:git@github.com:kamon-io/Kamon.git</connection>
  </scm>
  <developers>
    <developer><id>ivantopo</id><name>Ivan Topolnjak</name><url>https://twitter.com/ivantopo</url></developer>
    <developer><id>dpsoft</id><name>Diego Parra</name><url>https://twitter.com/diegolparra</url></developer>
  </developers>
}
